### PR TITLE
Constructor 0.51

### PR DESCRIPTION
**Pull request by hexarobi**
refactor file loaders into convertors

If I am updating an existing package...

- [ ] I have ensured that all modified files now have a different URL.
- [ ] If resources were modified, I also made sure to bump the `resources_version`.

### CODE REVIEW

**Comment by Sainan** [comment]
All you did is refactor code and call it a new major version? A refactor doesn't require an update at all.

**Comment by hexarobi** [comment]
> All you did is refactor code and call it a new major version? A refactor doesn't require an update at all.

This is to support other scripts

**Comment by Sainan** [comment]
Seems like this package may want to be split to create a separate "libconstructor", then.

**Comment by hexarobi** [comment]
> Seems like this package may want to be split to create a separate "libconstructor", then.

ya I was thinking the same thing. 👍

**Pull request merged**
