### PR TITLE
Add NovaLay

### PR DESCRIPTION
**Pull request by NovaPlays134**
Added Novalay
Changed the author name for all my scripts to Nova

If I am updating an existing package...

- [x] I have ensured that all modified files now have a different URL.
- [ ] If resources were modified, I also made sure to bump the `resources_version`.

### CODE REVIEW

**Comment by Sainan** [comment]
Literally unusable

image

**Comment by Sainan** [comment]
For `get_ip_data`, why not use soup.netIntel? Everything needed for GeoIP is already loaded in memory, HTTP request is a waste.

**Comment by NovaPlays134** [comment]
ill look into it thanks.

**Comment by NovaPlays134** [comment]
changed zone to show the label key
and changed the get_ip_data function

**Comment by Sainan** [comment]
Ah, and I guess you haven't seen this. Enable developer preset!!!

image

`get_max_wanted_level` does not take any arguments. I'd suggest just hard-coding 5 because who cares.

**Comment by NovaPlays134** [comment]
alright ill push a update tomorrow with the wanted level change and the zone name scaling

**Comment by NovaPlays134** [comment]
Okay I added a scale function for the zone name and hard-coded the max wanted level to 5.

**Comment by NovaPlays134** [comment]
Only small problem that I can not prevent is that the scaled text may not be that clear to read but atleast its not overlapping now.

**Pull request merged**
