### PR TITLE
Add DOLOS, a trolling script

### PR DESCRIPTION
**Pull request by thebitwise**
If I am updating an existing package...

- [x] I have ensured that all modified files now have a different URL.
- [x] If resources were modified, I also made sure to bump the `resources_version`.

### CODE REVIEW

**Comment by Sainan** [comment]
Why not add a "Dolos" list under "Trolling"?

**Comment by Sainan** [comment]
Also very funny thing happens when enabling Pharaoh's Curse on a modder. :D

**Comment by thebitwise** [comment]
That shouldn't have that check there, and I'll move the root, one sec

**Comment by thebitwise** [comment]
Should be good now

**Pull request merged**
