### PR TITLE
add docker instructions

### PR DESCRIPTION
**Pull request by hexarobi**
If I am updating an existing package...

- [ ] I have ensured that all modified files now have a different URL.
- [ ] If resources were modified, I also made sure to bump the `resources_version`.

### CODE REVIEW

**Comment by Sainan** [comment]
What is this useful for? This is just adding bloat in the form of apache2 and docker, and I don't see what problems are being solved by it.

**Comment by hexarobi** [comment]
It is just an optional alternative to installing PHP directly. If you have Docker installed already, then it's just a one-line command to get the server running. I figured it could save people time that want to go that route to have the proper command in the README.

**Comment by Sainan** [comment]
Docker seems like such an immense amount of bloat to solve a problem that doesn't exist. In fact, it seem to introduce more problems because the "docker" CLI doesn't seem to start the docker daemon automatically, instead just fails.

Anyway, this command doesn't even work on my machine:
> docker: Error response from daemon: create ${PWD}: "${PWD}" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.

You'd have to do this, instead:
```
docker run -d -p 80:80 -v "%cd%:/var/www/html" php:7.2-apache
```

**Comment by Sainan** [comment]
Closing due to inactivity.

**Pull request closed without merging**
