### PR TITLE
ChatCommander update

### PR DESCRIPTION
**Pull request by hexarobi**
- Fix error for missing class on croquette

If I am updating an existing package...

- [ ] I have ensured that all modified files now have a different URL.
- [ ] If resources were modified, I also made sure to bump the `resources_version`.

### CODE REVIEW

**Comment by Sainan** [comment]
You need to bump the version.

**Comment by Sainan** [comment]
Btw., I did tell you the new class name is "classic", it's also documented now.

**Comment by hexarobi** [comment]
> Btw., I did tell you the new class name is "classic", it's also documented now.

cool. will it be added to the joatt dictionary? this update skips over the vehicle if the class is nil, but if needed i can add some custom code for it maybe

**Comment by Sainan** [comment]
Vehicle classes are not the joaat dictionary. The only guarantee you are given is that they are valid Stand label hashes, and this still holds.

**Pull request merged**
