### PR TITLE
ChatCommander 0.18

### PR DESCRIPTION
**Pull request by hexarobi**
If I am updating an existing package...

- [x] I have ensured that all modified files now have a different URL.
- [x] If resources were modified, I also made sure to bump the `resources_version`.

### CODE REVIEW

**Comment by Sainan** [comment]
That's a pretty stupid description.

**Comment by hexarobi** [comment]
> That's a pretty stupid description.

any suggestions to improve?

**Comment by Sainan** [comment]
Something that justifies why one might want to download this instead of just using the builtin feature?

**Comment by hexarobi** [comment]
> Something that justifies why one might want to download this instead of just using the builtin feature?

Hmm, hard to explain that in one line. 

> Something that justifies why one might want to download this instead of just using the builtin feature?

How about "Expose chat commands to other players, alternative to built-in chat commands."?

**Comment by Sainan** [comment]
What do you mean with "automated lobby-finding while AFK"?

**Comment by hexarobi** [comment]
> What do you mean with "automated lobby-finding while AFK"?

there's an "AFK" mode that will check every few minutes to see if you are alone in a lobby, if so it will issue a `gopub` command to find a new lobby and give it a few mins for people to join before trying again. the intent is to not get stuck in a private lobby that no one else can join while AFK.

**Comment by Sainan** [comment]
That's forumulated a bit awkardly and I feel like could be a slight vector of abuse combined with "announcements."

**Comment by hexarobi** [comment]
> That's forumulated a bit awkardly and I feel like could be a slight vector of abuse combined with "announcements."

The announcements can't be configured to trigger more often than once every 30 mins. Someone could edit the script directly, but if they can figure that out its pretty trivial to write their own announcement script. Are you saying I shouldn't mention it in the description, or that it needs to be removed from the script before being shared on repo?

**Comment by Sainan** [comment]
My concern was only about the description. It looks fine now. I will look at the actual script tomorrow.

**Comment by Sainan** [comment]
It seems all the lib/ChatCommands/player files are cooked:
> Failed to fetch hexarobi/stand-lua-chatcommander@c59ed1bd655219649a295056449ba870e1be8ad5lib from GitHub.

**Comment by hexarobi** [comment]
> It seems all the lib/ChatCommands/player files are cooked

Hmm must have done something weird when bulk editing, but should be fixed now.

**Comment by Sainan** [comment]
You cannot use `https://` here as we don't use fully qualified URLs.

**Comment by Sainan** [comment]
Although there is also an "Auto-Announcements" option in the settings which is off by default? What's the point of an announcement being "enabled" exactly?

**Comment by Sainan** [comment]
It really seems to me like your script has at least 2 settings in completely disjointed places for every single piece of functionality, which just seems really odd.

**Comment by hexarobi** [comment]
> It really seems to me like your script has at least 2 settings in completely disjointed places for every single piece of functionality, which just seems really odd.

I moved the announcements settings into the announcements section. Any other places you suggest?

**Comment by Sainan** [comment]
The announcement settings definitely look better now. You have a similar thing with the commands having "Enabled", "Enabled For", and then "Authorized For" in a completely different spot.

**Comment by hexarobi** [comment]
> The announcement settings definitely look better now. You have a similar thing with the commands having "Enabled", "Enabled For", and then "Authorized For" in a completely different spot.

rearranged things a bit to hopefully make it clearer. there is a general authorized for option, that controls global access to all chat commands, like if you want it for friends-only. the specific access controls access to specific commands, so you can make certain commands only for friends, or blessed users.

**Comment by Sainan** [comment]
I also don't quite understand the "Help" action on commands. It has the same help text as the list and "Run" action, and does nothing when I click it.

**Comment by hexarobi** [comment]
> I also don't quite understand the "Help" action on commands. It has the same help text as the list and "Run" action, and does nothing when I click it.

clarified the help text on these options. The `Run` option is for executing the command without typing it, and ignoring all restrictions. The `Help` option is similar for executing the `!help` for the command without typing it. Useful for debugging things mostly.

**Comment by Sainan** [comment]
If that is supposed to print to something in chat, it is broken without any indication in SP.

**Comment by hexarobi** [comment]
> If that is supposed to print to something in chat, it is broken without any indication in SP.

Added a util.toast() to go with it and make it clearer what is triggering. I assume in SP there is no chat box so you can't see any output. This is generally intended to be used in MP, not SP.

**Comment by Sainan** [comment]
It seems "Passthrough Commands" are outright broken:
```
[13/06/2024 19:51:30] [string "ChatCommander.lua"]:961: bad argument #1 to 'get_children' (CommandRef expected, got nil)
stack traceback:
	[C]: in field 'get_children'
	[string "ChatCommander.lua"]:961: in field 'add_passthrough_command_menu'
	[string "ChatCommander.lua"]:927: in function <[string "ChatCommander.lua"]:925>
	[C]: in function 'xpcall'
	[string "Stand Lua Runtime"]:22: in function 'internal_xpcall_ioiqocsdvv'
	[string "Stand Lua Runtime"]:28: in function <[string "Stand Lua Runtime"]:27>
[13/06/2024 19:51:31] [string "ChatCommander.lua"]:935: Cannot create new commands in this context
stack traceback:
	[C]: in method 'list'
	[string "ChatCommander.lua"]:935: in field 'add_passthrough_command_menu'
	[string "ChatCommander.lua"]:927: in function <[string "ChatCommander.lua"]:925>
	[C]: in function 'xpcall'
	[string "Stand Lua Runtime"]:22: in function 'internal_xpcall_ioiqocsdvv'
```

They don't seem to save, and the "Delete" button doesn't work.

**Comment by hexarobi** [comment]
> It seems "Passthrough Commands" are outright broken:

Thx, I had made an update that broke some stuff, so made some more and I think this is working now.

**Comment by Sainan** [comment]
It seems to still be kinda broken: This part is only generated after restarting the script, not when initially creating the command.

image

**Comment by hexarobi** [comment]
> It seems to still be kinda broken: This part is only generated after restarting the script, not when initially creating the command.
> 
> image

Ya, I was hoping nobody would notice ;) ended up redoing things a bit to make that work better, now the Chat Commands menu is based off your files and only updates when reloading script. The Passthrough Commands menu is dynamic and can be edited, and they dont mix.

**Pull request merged**
