### PR TITLE
Update constructor 0.37.1

### PR DESCRIPTION
**Pull request by hexarobi**
- Fix bug with free edit mode
- Update updater to use async_http.have_access

If I am updating an existing package...

- [x] I have ensured that all modified files now have a different URL.
- [x] If resources were modified, I also made sure to bump the `resources_version`.

### CODE REVIEW

**Comment by hexarobi** [comment]
> Given that you need auto-updater for "Install Curated Constructs", and I assume you just "fixed" this option, it's curious that it's still broken in 0.37.1.
> 
> image

hmm do you have any more details on this error? trying to reproduce or figure out what it could have been, but so far nothing. the command ref should be fixed in auto-updater 2.5.11 and that seems to be what is linked in this PR, can you confirm that is the version that you have?

**Comment by Sainan** [comment]
Just install 0.37.1 from the repository (using the development steps in the readme)

**Comment by hexarobi** [comment]
> Just install 0.37.1 from the repository (using the development steps in the readme)

Thanks for catching that =) Got PHP running locally and was able to debug and found and fixed the error. Version updated to 0.37.2r

**Comment by Sainan** [comment]
That works now. Unfortunately, this part of auto-updater is not acceptable:

image

**Comment by hexarobi** [comment]
> That works now. Unfortunately, this part of auto-updater is not acceptable:
> 
> image

Hmm ok, that part isn't new, but I understand. I will work on that.

**Pull request merged**
