### PR TITLE
Constructor 0.50

### PR DESCRIPTION
**Pull request by hexarobi**
If I am updating an existing package...

- [ ] I have ensured that all modified files now have a different URL.
- [ ] If resources were modified, I also made sure to bump the `resources_version`.

### CODE REVIEW

**Comment by Sainan** [comment]
You should also declare the dependency of `lua/json`. Btw., you don't need a dependency for this at all, you can just `require "pluto:json"`.

**Comment by hexarobi** [comment]
> You should also declare the dependency of `lua/json`. Btw., you don't need a dependency for this at all, you can just `require "pluto:json"`.

Updated to
```
util.ensure_package_is_installed('lua/json')
local json = require_dependency("json")
```
I tried 
```
local json = require "pluto:json"
```
instead but this still crashes me 100% of the time

**Comment by Sainan** [comment]
`util.ensure_package_is_installed` is not the way dependencies for repository packages should be declared.

Also, do you have steps to reproduce the crash with Pluto's JSON library?

**Comment by hexarobi** [comment]
> `util.ensure_package_is_installed` is not the way dependencies for repository packages should be declared.
> 
> Also, do you have steps to reproduce the crash with Pluto's JSON library?

I reproduce it currently by scrollling through a list of JSON constructs. I can try to narrow down exactly what file is causing it and make a stand-alone example script, but I haven't had a chance to do that yet, so for now just trying to stop the crashes.

What is the better way?

**Comment by Sainan** [comment]
Literally just add it to the `depends` array.

**Comment by hexarobi** [comment]
> Literally just add it to the `depends` array.

Any docs for that or examples?

```
local depends = {
  "lua/json",
  ...
}
```
?

**Comment by Sainan** [comment]
Bro, a package on the repository has all its dependencies installed before your code is even run.

**Comment by hexarobi** [comment]
> Bro, a package on the repository has all its dependencies installed before your code is even run.

Ah its because I still support running this outside of the repo. But ya that makes sense, maybe I can figure out how to retire that.

**Comment by hexarobi** [comment]
Added `lua/json` and `lua/ScaleformLib` to depends list. Reworked requires to be simpler across the board. Got rid of dev branch to simplify down to just main git and repo (stable) version

**Comment by Sainan** [comment]
Could you verify that the crash issue is now resolved on the latest build, and use the `pluto:json` library, instead, if you have no other reason to use `lua/json`?

**Comment by hexarobi** [comment]
> Could you verify that the crash issue is now resolved on the latest build, and use the `pluto:json` library, instead, if you have no other reason to use `lua/json`?

yes looks good in latest. updated to use pluto json

**Pull request merged**
