### PR TITLE
Update packages.php added NovaHook

### PR DESCRIPTION
**Pull request by NovaPlays134**
If it gets added to the repository i will delete the auto updater inside the script as fast as i can.

If I am updating an existing package...

- [x] I have ensured that all modified files now have a different URL.
- [x] If resources were modified, I also made sure to bump the `resources_version`.

### CODE REVIEW

**Comment by NovaPlays134** [comment]
what do you mean with URL is not versioned? and i will remove the auto-updating logic

**Comment by NovaPlays134** [comment]
all the issues should been fixed i removed the get_session_code and ill look into util.is_session_started later

**Comment by Sainan** [comment]
Basically, my issue was with this code in particular: https://github.com/NovaPlays134/NovaHook/blob/243852c914febbb9aad460af00f0cc403be225e5/NovaHook.pluto#L113-L118
The `if session_code == "N/A"` could easily be replaced with `if not util.is_session_started()`

Although, now that you made me aware of show_session_code_when_new_session, that logic should definitely also be improved to not request a session code unless absolutely needed.

Also, in the future, don't re-tag versions. Always bump & make a new tag.

**Comment by NovaPlays134** [comment]
okay thanks, i appreciate your help

**Comment by Sainan** [comment]
Anyway, I guess you did "fix the issue" by just pressing delete on it.

Error when running after installed with this manifest tho:
image

**Comment by NovaPlays134** [comment]
im sorry for this 😅 but it should be fixed and i made it version 1.1 now instead of making a new 1.0 version

**Comment by Sainan** [comment]
https://semver.org/

**Comment by NovaPlays134** [comment]
the next time i will make the version semantic versioning 😂 thx

**Comment by NovaPlays134** [comment]
I tested this before i pushes this and it seemed to work fine for me, ill look into it why it does not work for you.

**Comment by Sainan** [comment]
Maybe because there's no "NovaHook" folder in my store dir.

**Comment by NovaPlays134** [comment]
i'm quite the idiot that i did not think of that

**Comment by Sainan** [comment]
It finally loaded.

- I can see "Set Webhook Url" and "Set New Webhook URL" — two options for the same thing?
- "Check for Update" and "Clean Reinstall" still exist, but error upon click.

**Comment by NovaPlays134** [comment]
I removed "Check for Update" and "Clean Reinstall" and for the "Set Webhook Url" is for when notting is set yet and "Set New Webhook URL" is to put a new webhook they are the same just different names, i made the change that only 1 of these show up at the time so people don't get confused.

**Comment by Sainan** [comment]
Not me wasting like 16 minutes trying to figure out why the HTTP request isn't going through when I have "Disable internet access" set.

**Comment by NovaPlays134** [comment]
oh haha, i could maybe add in the future that it enables the "Disable internet access" toggle when the script starts and when it closes it sets it to the state it was. for now i will leave it as it is and the script fully works for me now let me know if you have any issues

**Comment by Sainan** [comment]
Scripts can't change it, and it's not your fault, the API really should be better about this.

**Comment by NovaPlays134** [comment]
ah alright i didn't know scripts can't change it.

**Comment by NovaPlays134** [comment]
ofc it is didn't think that far, and thanks for taking your time.

**Pull request merged**
