### PR TITLE
Add SlotBot

### PR DESCRIPTION
**Pull request by hexarobi**
Add SlotBot to lua scripts repo

If I am updating an existing package...

- [x] I have ensured that all modified files now have a different URL.
- [x] If resources were modified, I also made sure to bump the `resources_version`.

### CODE REVIEW

**Comment by Sainan** [comment]
Since this is a money-related scriptl, please share some information about the ban tests you have performed.

**Comment by hexarobi** [comment]
> Since this is a money-related script, please share some information about the ban tests you have performed.

I've tested it myself several times over the course of development. It relies on reading the chip counts and keeping track of totals won and preventing from going over the configured amount (default 45mil) per 24 hours period. It is mostly just clicking existing options in the game or stand, so the user doesn't have to. It has been posted in the Stand disc for almost 6 months now, with 70+ reactions, without a corresponding rash of ban reports. There is a warning about anti-cheat flags on the account.

**Comment by Sainan** [comment]
Not acceptable, script has auto-updating logic.

**Comment by Sainan** [comment]
idk why you don't just use a menu.hyperlink... readonly value is meant to have a value 😒 

image

**Pull request merged**
