### PR TITLE
JinxScript 0.51

### PR DESCRIPTION
**Pull request by Prisuhm**

### CODE REVIEW

**Comment by Sainan** [comment]
Pushing code without testing it, are we?

**Comment by Prisuhm** [comment]
its just global changes, the rest has been tested prior to the gta update ¯\_(ツ)_/¯

**Comment by Prisuhm** [comment]
I will wait to test though I guess

**Comment by Prisuhm** [comment]
ah yea, you were right. shouldve waited. it seems my weapon damage event address is outdated now so ill need to fix that. my apologies.

**Pull request closed without merging**
